#pragma once

#include "grid/multires_mac_grid3d.h"
#include "particles/particles3d_tp.h"
#include "pressure/multires_pressure3d.h"
#include "physics/phasefield.h"

struct MRSim3DTP {
  MRLayout3D<4> layout;
  MRMacGrid3D<4> grid;
  Particles3DTP particles;
  PhaseParams phase;
  double dt = 0.02;
  double gravity = -9.81;
  double Vp = 1.0;
  double alpha_liquid = 0.95;
  double alpha_gas = 0.95;
  int cg_iters = 160;
  double cg_tol = 1e-7;
  double cg_rel_tol = 1e-6;
  bool cg_jacobi_preconditioner = true;
  bool cg_flexible_beta = false;
  bool cg_adaptive_restart = true;
  double cg_restart_growth = 10.0;
  int cg_relaxation_sweeps = 0;
  double cg_relaxation_omega = 0.67;
  double cg_relaxation_min_omega = 0.05;
  int cg_residual_history_stride = 0;
  int cg_residual_history_limit = 64;
  bool cg_coarse_correction = false;
  int cg_coarse_correction_iters = 32;
  int cg_coarse_correction_sweeps = 1;
  double cg_coarse_correction_abs_tol = 0.0;
  double cg_coarse_correction_rel_tol = 1e-3;
  double cg_coarse_correction_min_scale = 1.0 / 64.0;
  bool cg_coarse_preconditioner = false;
  int cg_coarse_preconditioner_iters = 8;
  double cg_coarse_preconditioner_abs_tol = 0.0;
  double cg_coarse_preconditioner_rel_tol = 1e-2;
  double cg_coarse_preconditioner_scale = 1.0;
  double cg_coarse_preconditioner_min_rz_gain = 0.0;
  double cg_coarse_preconditioner_max_work_ratio = 0.0;
  bool cg_coarse_preconditioner_auto_disable = false;
  int cg_coarse_preconditioner_auto_disable_after = 4;
  bool dynamic_refinement = true;
  int dynamic_particle_padding = 1;
  int dynamic_gas_padding = 2;
  int dynamic_hysteresis_cells = 1;
  int dynamic_max_fine_leaves = 0;
  bool dynamic_budget_limited = false;
  int dynamic_last_fine_leaves = 0;
  bool dynamic_retained_box_valid = false;
  int dynamic_retained_x0 = 0;
  int dynamic_retained_y0 = 0;
  int dynamic_retained_z0 = 0;
  int dynamic_retained_x1 = 0;
  int dynamic_retained_y1 = 0;
  int dynamic_retained_z1 = 0;
  bool narrow_band_air = false;
  int narrow_band_air_radius = 2;
  int narrow_band_air_removed_last = 0;
  int narrow_band_air_removed_total = 0;
  int narrow_band_air_liquid_cells_last = 0;
  int narrow_band_air_gas_particles_before_last = 0;
  int narrow_band_air_gas_particles_after_last = 0;
  bool gas_particle_coarsening = false;
  int gas_particles_per_cell_target = 4;
  unsigned int gas_particle_coarsening_seed = 0x9e3779b9u;
  int gas_particle_coarsening_removed_last = 0;
  int gas_particle_coarsening_removed_total = 0;
  int gas_particle_coarsening_cells_last = 0;
  int gas_particle_coarsening_overfull_cells_last = 0;
  int gas_particle_coarsening_before_last = 0;
  int gas_particle_coarsening_after_last = 0;
  bool liquid_particle_coarsening = false;
  int liquid_particles_per_cell_target = 4;
  unsigned int liquid_particle_coarsening_seed = 0x7f4a7c15u;
  int liquid_particle_coarsening_removed_last = 0;
  int liquid_particle_coarsening_removed_total = 0;
  int liquid_particle_coarsening_cells_last = 0;
  int liquid_particle_coarsening_overfull_cells_last = 0;
  int liquid_particle_coarsening_before_last = 0;
  int liquid_particle_coarsening_after_last = 0;
  bool liquid_particle_refill = false;
  bool liquid_particle_refill_interface_only = false;
  int liquid_particle_refill_interface_radius = 1;
  int liquid_refill_particles_per_cell_target = 4;
  unsigned int liquid_particle_refill_seed = 0x6a09e667u;
  int liquid_particle_refill_added_last = 0;
  int liquid_particle_refill_added_total = 0;
  int liquid_particle_refill_cells_last = 0;
  int liquid_particle_refill_interface_cells_last = 0;
  int liquid_particle_refill_underfull_cells_last = 0;
  int liquid_particle_refill_before_last = 0;
  int liquid_particle_refill_after_last = 0;
  MRPressureSolveStats3D last_pressure_stats;

  MRSim3DTP(int nx, int ny, int nz, double dx);
  void initBubbleTankInterfaceBand();
  void applyNarrowBandAir();
  void applyGasParticleCoarsening();
  void applyLiquidParticleCoarsening();
  void applyLiquidParticleRefill();
  void applyParticleAdaptivity();
  void updateDynamicRefinement();
  void step();
  int activePressureCellCount() const;
  int uFaceCount() const;
  int vFaceCount() const;
  int wFaceCount() const;
};
